title: "Hühner & Katzen"
pages: ./quelle/seiten
images: ./quelle/bilder
assets: ./quelle/statisch
templates: ./templates
output: ./docs

image_sizes: 
  - 600
  - 200
  - 80

menu:
  - title: Start
    href: ./
    img: ./images/home-80.png
  - title: Katzen
    href: ./seite1.html
    img: ./images/katze-80.jpg
  - title: Hühner
    href: ./seite2.html
    img: ./images/huhn-80.jpg
  - title: Axolotl
    href: ./seite3.html
    img: ./images/axolotl-80.jpg