title: "Hühner & Katzen"
pages: ./quelle/seiten
images: ./quelle/bilder
assets: ./quelle/statisch
templates: ./templates
output: ./docs

image_sizes: 
  - 1920
  - 200

menu:
  - title: Start
    href: ./
    img: ./images/home-200.png
  - title: Katzen
    href: ./seite1.html
    img: ./images/katze-200.jpg
  - title: Hühner
    href: ./seite2.html
    img: ./images/huhn-200.jpg
  - title: Axolotl
    href: ./seite3.html
    img: ./images/axolotl-200.jpg